### ISSUE TITLE
Can't deploy Opencti with docker-compose

### ISSUE THREAD

**Issue by Mav1814** [OpenCTI-Platform/docker#265]
I've been trying to deploy opencti through docker-compose, but so far I've been unsuccessful. I've tried several ways and always to no avail. The workers keep restarting, with the error 

```
ConnectionError: HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c8962e120>: Failed to establish a new connection: [Errno 111] Connection refused'))", "taskName": null}

Traceback (most recent call last):
  File "/opt/opencti-worker/worker.py", line 580, in <module>
    worker = Worker()
             ^^^^^^^^
  File "<string>", line 6, in __init__
  File "/opt/opencti-worker/worker.py", line 499, in __post_init__
    self.api = OpenCTIApiClient(
               ^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pycti/api/opencti_api_client.py", line 203, in __init__ raise ValueError(ValueError: OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```
The default connectors also keep restarting with the error

```
ConnectionError: HTTPConnectionPool(host='opencti', port=8080): Max retries exceeded with url: /graphql (Caused by NameResolutionError(
\"<urllib3.connection.HTTPConnection object at 0x7f8b8096c510>: Failed to resolve 'opencti' ([Errno -2] Name does not resolve)\"))"}
connector-import-file-stix_1  | OpenCTI API is not reachable. Waiting for OpenCTI API to start or check your configuration...
```
I need some help. I even try it in a clean VM. 

Docker-compose file, is the same as the repository. My env is this.

```
OPENCTI_ADMIN_EMAIL=admin@test
OPENCTI_ADMIN_PASSWORD= n5CE8aLBri
OPENCTI_ADMIN_TOKEN=0571e878-f584-4140-be9c-f47d8a7167b9
OPENCTI_BASE_URL=http://10.0.2.68:8080
MINIO_ROOT_USER=opencti
MINIO_ROOT_PASSWORD=eH7zfQRzehx
RABBITMQ_DEFAULT_USER=opencti
RABBITMQ_DEFAULT_PASS=NWN35eMBj
CONNECTOR_EXPORT_FILE_STIX_ID=3ee334e1-9545-4c65-9f01-210edef11118
CONNECTOR_EXPORT_FILE_CSV_ID=a33db09d-1013-453f-86f0-3b55993735ed
CONNECTOR_EXPORT_FILE_TXT_ID=20affd46-98ef-4778-b62f-6bbf80d659c4
CONNECTOR_IMPORT_FILE_STIX_ID=afe70a85-d6a6-46a2-9f24-f4b8c57a903a
CONNECTOR_IMPORT_DOCUMENT_ID=76b2d5e5-f297-4ac7-9b95-f0972ac6f530
SMTP_HOSTNAME=localhost
ELASTIC_MEMORY_SIZE=4G
```

What could be the issue?

**Comment by MarbellHosting** [comment]
Same issue.  Installed and reinstalled from a clean VM.  Tried docker-compose up -d, docker swarm, running from portainer.  

The exact same services reported in this thread are restarting.  Previous issue #5159 reported the same problem.  The "fix" in that issue was to install it manually.  The problems with the docker install that were reported in that issue were not addressed.

**Comment by MarbellHosting** [comment]
I found a way.  Ping me.

**Comment by Namtv2312** [comment]
> I found a way. Ping me.

help me, pls.

**Comment by AmitKulkarni9** [comment]
@MarbellHosting can you post it here how did you resolve this. getting same error.

**Comment by MarbellHosting** [comment]
Check this:  https://benheater.com/proxmox-running-opencti/
Forget about the proxmox specific setup and scroll down to:  Installing OpenCTI

I already had docker installed.  So I added the user.

Then as the new user:
    1  cd /opt/opencti/
    2  wget https://github.com/OpenCTI-Platform/docker/raw/master/docker-compose.yml -O docker-compose.yml
    3  nano docker-compose.yml
    4  cat << EOF > .env  ( follow the .env setup instructions )
   20  EOF
   21  nano .env
   24  docker-compose up -d
   25  netstat -tulpn
   26  docker ps


Why did it work?  Perhaps due to the docker-compose.yml in this setup guide, or due to using a openctl_svc user
and running from /opt/opencti/

I later heavily edited the compose file and env as needed.
